import AuthContext from './context/AuthContext'
import './globals.css'
import ToasterContext from './context/ToasterContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
          {typeof window === 'undefined' && (
            <style
              id="holderStyle"
              dangerouslySetInnerHTML={{
                __html: `
          *, *::before, *::after {
            transition: none!important;
          }
          `,
              }}
            />
          )}
        </head>
      <body>
        <AuthContext>
          <ToasterContext />
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
